### ISSUE TITLE
Help understanding callbacks in user entities

### ISSUE THREAD

**Issue by KameronKales** [dtesler/node-api.ai#1]
David-

Id love some help understanding how to format a callback. I need to set my bot up to respond based on an entity and am getting problems around the callback

**Comment by dtesler** [comment]
Hey Kameron -- sorry for the late reply, I would've replied immediately, but I woke up late :P

Can you post the code causing the issues?

**Comment by KameronKales** [comment]
Hi david. Can you help me understand how to use the api.ai in my facebook messenger bot? I need to set up the app.js file I have so that when I message my bot on fb it uses the NLp from api.ai to do small talk.

**Comment by dtesler** [comment]
So, are you trying to set up the small talk domain?

Try this:

### First, head to domains in your api.ai console and enable small talk

![](http://i.imgur.com/4JWVu3J.png)

### Next, head to settings to fetch your client API key

![](http://i.imgur.com/FvqT7ms.png)

### Find it, and copy it

![](http://i.imgur.com/mTuJUXf.png)

### Now, with your client access token, create a new api.ai object

``` javascript
var apiai = require("api.ai");

var nlp = new apiai({
    token: "{PASTE CLIENT TOKEN HERE}"
});
```

### Now, you will be able to make requests from your bot as such:

``` javascript
var message = "lol";

nlp.text(message, function (err, response) {

    if (err) return console.log(err.stack); //=> Handle error

    else {
        // Your code to respond to message
        console.log(response.result.fulfillment.speech); //=> Will log something like "Jokes included free of charge."
    }

});
```

Let me know if this helps.

Cheers,
David
