### ISSUE TITLE
sessionId is not set

### ISSUE THREAD

**Issue by uriva** [dtesler/node-api.ai#2]
```
const msg = 'hi';
const nlp = new apiai({
  token: 'my_client_token',
  session: '1'
});
const apiairesponse = await nlp.text(msg);
console.log(apiairesponse);
```

Getting this error:
"errorDetails": "Required 'sessionId' parameter is empty."

**Comment by dcsan** [comment]
should the session be when the object is created?
surely you would want to create one client 'object' and then reuse that for each request. So the session should be set in the request, not the object instantiation.

**Comment by dcsan** [comment]
I get the same thing. I also tried actually naming the option correctly, 

session -> sessionId

BUT still same problem >.<

has this plugin every actually been used?

**Comment by dcsan** [comment]
looking at this source, it seems like this module is just a wrapper around the original (out of date now) api-ai official library, except for the fact its broken

**Comment by dtesler** [comment]
Apologies for my 3am code.

Issue should now be patched for text requests.
Feel free to reopen this issue if otherwise.

 +1 to @dcsan for pointing out the cause.
